### ISSUE TITLE
add a default location to show time series plot upfront

### ISSUE THREAD

**Issue by jli-99** [nasa-nccs-hpda/eis-dashboard#9]
**Is your feature request related to a problem? Please describe.**
Dashboard requires user to pick a location first, then display time series plot, which is sort of counterintuitive.

**Describe the solution you'd like**
Have a default location set up, and show TS plots right after user selected variable and data rendering completed.

**Describe alternatives you've considered**
Or,
Show a straight line at plot area as a place holder and waiting for user to pick location.

**Additional context**
This is a feed back from Denis.

**Comment by cssprad1** [comment]
Done with #10
